---
title: "Como montar meu banco de dados?"
date: 16 de agosto de 2016
header-includes:
   - \setbeamertemplate{navigation symbols}{}
   - \author[Eduardo Junior, Henrique Laureano]{Eduardo Elias Ribeiro Junior
                                                \and Henrique Aparecido Laureano}
output: 
  beamer_presentation: 
    colortheme: dove
    fonttheme: serif
    highlight: kate
    incremental: yes
    keep_tex: yes
    theme: Madrid
    toc: yes
---

```{r setup, include=FALSE}
library(knitr)

tema <- knit_theme$get("acid")

knit_theme$set(tema)

opts_chunk$set(size='small'
               , cache=TRUE, cache.path='cache/'
               , comment=NA, warning=FALSE, message=FALSE
               , fig.align='center', fig.width=8, fig.height=4.5
               , dpi=100, fig.path='iBagens/', fig.pos='H'
               , background='#ffffff'
               , results='hold', fig.show='hold')
```

# O que é um banco de dados?

## Definição

> Um banco de dados é uma coleção organizada de dados que se relaciona de forma a criar
  algum sentido (informação) e dar mais eficiência durante uma pesquisa ou estudo

\vfill

Simplificando:

\vspace{.75cm}

> Banco de dados é uma coleção de dados interligados entre si e organizados para
  fornecer informações

## Dados *vs* Informações

\[ {\rm Dados} \neq {\rm Informações} \]

Dados:

\vspace{.25cm}

> Fatos brutos, em sua forma primária. Muitas vezes os dados podem não fazer sentido
  sozinhos

\vspace{.5cm}

Informações:

\vspace{.25cm}

> Consiste no agrupamento de dados de forma organizada para fazer sentido, gerar
  conhecimento

\vfill

Um banco de dados é uma estrutura de dados organizada que permite a extração de
informações

# Qual o ponto de partida?

## Definições iniciais

* Qual o objetivo do estudo? \vspace{.2cm}

    + O que se deseja estudar? \vspace{.2cm}

    + Qual a hipótese a ser testada? \vspace{.2cm}

        - Qual(is) possível(is) diferença(s) deseja-se verificar?

\vspace{.5cm}

* Com seus objetivos definidos, quais características dos pacientes precisam ser
  avaliadas / mensuradas? \vspace{.2cm}
  
    + Se for para pecar, peque por excesso \vspace{.2cm}

        - É preferível ter mais informações mensuradas. Assim não se corre o risco
          de inviabilizar uma possível análise pela ausência do registro de
          informações

# Como organizar meu banco de dados?

## Como organizar meu banco de dados?

* Nas linhas os pacientes (unidades experimentais) \vspace{.3cm}

* Nas colunas suas informações avaliadas / mensuradas \vspace{.3cm}

* Cada informação mensurada deve ter sua própria coluna no banco de dados
  \vspace{.3cm}

* E se o paciente foi avaliado mais de uma vez em ao menos uma característica?
  \vspace{.3cm}

    + Ele deve receber uma nova linha no banco de dados, de preferência logo na linha
      abaixo \vspace{.3cm}
      
    + Nas características que não foram novamente avaliadas repete-se o valor
      (observação)

# Alguns exemplos

## Exemplo 1